graphql:
  packages: "org.bjartek.graphql"
  subscriptions:
    # Send a ka message every 1000 ms (1 second)
    keepAliveInterval: 1000

spring:
  application:
    name: kotlin-graphql-experiment

integrations:
  mokey:
    url : http://foo
  unclematt:
    url : http://foo
  cantus:
    url : http://foo
  dbh:
    url : http://foo
aurora:
  token:
    value: token